export const TIPO_EMPRESA = {
  DOADORA: "DOADORA",
  RECEBEDORA: "RECEBEDORA"
}

export const STATUS_EMPRESA = {
  ATIVA: 1,
  SUSPENSA: 2,
  INATIVA: 3
}

export const CATEGORIA_RECEBEDORA = {
  ONG: 1,
  OSC: 2,
  RELIGIOSA: 3,
  BANCODEALIMENTOS: 4
}

export const CATEGORIA_DOADORA = {
  RESTAURANTE: 1,
  HORTIFRUTTI: 2,
  MERCADO: 3,
  PADARIA: 4,
  FASTFOOD: 5,
  ADEGA: 6
}